import { ChevronRight, FileText, Search } from 'lucide-react';
import type { SavedMeetingDocument } from '@/lib/meeting-document';

export function MeetingLibrary({ meetings, view, query, onQuery, onOpen, onNew, locked }: {
  meetings: SavedMeetingDocument[]; view: 'meetings' | 'notes' | 'search'; query: string; onQuery: (query: string) => void;
  onOpen: (id: string) => void; onNew: () => void; locked: boolean;
}) {
  const matches = meetings.filter(meeting => `${meeting.title} ${meeting.transcript} ${meeting.notes} ${JSON.stringify(meeting.context)} ${(meeting.questions || []).join(' ')}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  const visible = query ? matches : meetings;
  return <><label className="meeting-search"><Search size={18} aria-hidden="true" /><input aria-label="Search meetings" value={query} onChange={event => onQuery(event.target.value)} placeholder="Search titles, transcripts, or notes…" /><kbd>⌕</kbd></label><div className="library-count">{visible.length} {visible.length === 1 ? 'conversation' : 'conversations'}</div><div className="meeting-list">{visible.length ? visible.map(meeting => <button className="saved-meeting-card" key={meeting.id} onClick={() => onOpen(meeting.id)} disabled={locked}><span className="library-meeting-icon"><FileText size={21} aria-hidden="true" /></span><div><h2>{meeting.title}</h2><span>{new Date(meeting.date).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })} · {Math.floor(meeting.elapsed / 60)}m {Math.floor(meeting.elapsed % 60)}s</span><p>{view === 'notes' ? meeting.notes || meeting.context.summary || 'No AI notes for this meeting. Open to review its transcript.' : meeting.context.summary || meeting.transcript.slice(0, 180)}</p><div className="library-topics">{meeting.context.topics.slice(0, 3).map((topic, index) => <span key={`${index}-${topic}`}>{topic}</span>)}</div></div><ChevronRight size={16} aria-hidden="true" /></button>) : <div className="library-empty"><span className="welcome-orbit"><FileText size={30} aria-hidden="true" /></span><h2>{query ? 'No matching meetings' : 'Your conversations belong here.'}</h2><p>{query ? 'Try another word from the title, transcript, or notes.' : 'Every conversation is a beginning. Record or upload your first meeting to find its next steps here.'}</p><button className="primary-button" onClick={onNew} disabled={locked}>New Meeting</button></div>}</div></>;
}
