export function WorkspaceSettings({ enabled, voiceEnabled, toggleEnabled, toggleVoice, retention, setRetention, meetingCount, locked, confirming, onDelete, onCancelDelete, onSignOut, accountEmail }: {
  enabled: boolean; voiceEnabled: boolean; toggleEnabled: () => void; toggleVoice: () => void;
  retention: 'device' | 'session'; setRetention: (value: 'device' | 'session') => void; meetingCount: number;
  locked: boolean; confirming: boolean; onDelete: () => void; onCancelDelete: () => void;
  onSignOut?: () => void; accountEmail?: string;
}) {
  return <>
    <div className="settings-card"><div><h2>AI clarifications</h2><p>Short, useful questions when a detail matters. Always wait for a pause.</p></div><button className={`ai-voice-toggle ${enabled ? 'is-active' : ''}`} aria-pressed={enabled} onClick={toggleEnabled}>AI Interruption: {enabled ? 'ON' : 'OFF'}</button></div>
    <div className="settings-card"><div><h2>Spoken questions</h2><p>Read questions on screen, or let Hush ask aloud.</p></div><button className={`ai-voice-toggle ${voiceEnabled ? 'is-active' : ''}`} aria-pressed={voiceEnabled} onClick={toggleVoice}>AI Voice: {voiceEnabled ? 'ON' : 'OFF'}</button></div>
    <div className="settings-card retention-settings"><div><h2>Meeting privacy</h2><p>Audio is kept only in this tab. {accountEmail ? 'Choose whether to save new transcripts and notes to your private account.' : 'Choose how long to keep transcripts and notes on this device.'}</p><label htmlFor="meeting-retention" className="visually-hidden">Meeting retention</label><select id="meeting-retention" value={retention} disabled={locked} onChange={event => setRetention(event.target.value as 'device' | 'session')}><option value="device">{accountEmail ? 'Save to my account' : 'Keep on this device'}</option><option value="session">Only this session</option></select><p className="retention-caption">{accountEmail ? retention === 'device' ? 'Private account storage, with a copy on this device. Signing out clears the device copy.' : 'New meetings stay in this tab. Previously saved account meetings remain until deleted.' : retention === 'device' ? 'Up to 30 meetings. Shared device? Choose session only.' : 'Reloading or closing this page removes session meetings.'}</p></div><span className="setting-value">{meetingCount} meetings</span></div>
    {!!meetingCount && <div className="privacy-actions">{confirming ? <div role="alert"><p>Delete all saved meetings from {accountEmail ? 'your account and this device' : 'this workspace'}? This cannot be undone.</p><button className="danger-button" onClick={onDelete} disabled={locked}>Confirm delete all meetings</button><button className="text-button" onClick={onCancelDelete} disabled={locked}>Keep meetings</button></div> : <button className="text-button" disabled={locked} onClick={onDelete}>Delete all saved meetings</button>}</div>}
    {onSignOut && <div className="account-settings"><p>{accountEmail}</p><button className="text-button" onClick={onSignOut} disabled={locked}>Sign out</button></div>}
  </>;
}
