export function WorkspaceSettings({ enabled, voiceEnabled, toggleEnabled, toggleVoice, retention, setRetention, meetingCount, locked, confirming, onDelete, onCancelDelete, onSignOut, accountEmail, frequency = 'balanced', setFrequency, language = 'auto', setLanguage, summaryStyle = 'concise', setSummaryStyle }: {
  enabled: boolean; voiceEnabled: boolean; toggleEnabled: () => void; toggleVoice: () => void;
  retention: 'device' | 'session'; setRetention: (value: 'device' | 'session') => void; meetingCount: number;
  locked: boolean; confirming: boolean; onDelete: () => void; onCancelDelete: () => void;
  onSignOut?: () => void; accountEmail?: string;
  frequency?: 'balanced' | 'minimal'; setFrequency?: (value: 'balanced' | 'minimal') => void;
  language?: 'auto' | 'en' | 'id'; setLanguage?: (value: 'auto' | 'en' | 'id') => void;
  summaryStyle?: 'concise' | 'structured'; setSummaryStyle?: (value: 'concise' | 'structured') => void;
}) {
  return <>
    <div className="settings-card"><div><h2>AI clarifications</h2><p>Short, useful questions when a detail matters. Always wait for a pause.</p></div><button className={`ai-voice-toggle ${enabled ? 'is-active' : ''}`} aria-pressed={enabled} onClick={toggleEnabled}>AI Interruption: {enabled ? 'ON' : 'OFF'}</button></div>
    <div className="settings-card"><div><h2>Clarification frequency</h2><p>How often Hush offers clarification questions during natural pauses.</p><label htmlFor="clarification-frequency" className="visually-hidden">Clarification frequency</label><select id="clarification-frequency" value={frequency} disabled={locked} onChange={event => setFrequency?.(event.target.value as 'balanced' | 'minimal')}><option value="balanced">Balanced (standard)</option><option value="minimal">Essential only (fewer interruptions)</option></select></div><span className="setting-value">{frequency === 'balanced' ? 'Standard' : 'Minimal'}</span></div>
    <div className="settings-card"><div><h2>Spoken questions</h2><p>Read questions on screen, or let Hush ask aloud.</p></div><button className={`ai-voice-toggle ${voiceEnabled ? 'is-active' : ''}`} aria-pressed={voiceEnabled} onClick={toggleVoice}>AI Voice: {voiceEnabled ? 'ON' : 'OFF'}</button></div>
    <div className="settings-card"><div><h2>Meeting language</h2><p>Language used for speech recognition and clarification questions.</p><label htmlFor="meeting-language" className="visually-hidden">Meeting language</label><select id="meeting-language" value={language} disabled={locked} onChange={event => setLanguage?.(event.target.value as 'auto' | 'en' | 'id')}><option value="auto">Auto detect (EN / ID)</option><option value="en">English</option><option value="id">Bahasa Indonesia</option></select></div><span className="setting-value">{language === 'auto' ? 'Auto' : language.toUpperCase()}</span></div>
    <div className="settings-card"><div><h2>Meeting notes style</h2><p>Choose the default layout for summary and key takeaways.</p><label htmlFor="summary-style" className="visually-hidden">Notes style</label><select id="summary-style" value={summaryStyle} disabled={locked} onChange={event => setSummaryStyle?.(event.target.value as 'concise' | 'structured')}><option value="concise">Concise bullet points</option><option value="structured">Structured overview</option></select></div><span className="setting-value">{summaryStyle === 'concise' ? 'Concise' : 'Structured'}</span></div>
    <div className="settings-card retention-settings"><div><h2>Meeting privacy</h2><p>Audio is kept only in this tab. {accountEmail ? 'Choose whether to save new transcripts and notes to your private account.' : 'Choose how long to keep transcripts and notes on this device.'}</p><label htmlFor="meeting-retention" className="visually-hidden">Meeting retention</label><select id="meeting-retention" value={retention} disabled={locked} onChange={event => setRetention(event.target.value as 'device' | 'session')}><option value="device">{accountEmail ? 'Save to my account' : 'Keep on this device'}</option><option value="session">Only this session</option></select><p className="retention-caption">{accountEmail ? retention === 'device' ? 'Private account storage, with a copy on this device. Signing out clears the device copy.' : 'New meetings stay in this tab. Previously saved account meetings remain until deleted.' : retention === 'device' ? 'Up to 30 meetings. Shared device? Choose session only.' : 'Reloading or closing this page removes session meetings.'}</p></div><span className="setting-value">{meetingCount} meetings</span></div>
    {!!meetingCount && <div className="privacy-actions">{confirming ? <div role="alert"><p>Delete all saved meetings from {accountEmail ? 'your account and this device' : 'this workspace'}? This cannot be undone.</p><button className="danger-button" onClick={onDelete} disabled={locked}>Confirm delete all meetings</button><button className="text-button" onClick={onCancelDelete} disabled={locked}>Keep meetings</button></div> : <button className="text-button" disabled={locked} onClick={onDelete}>Delete all saved meetings</button>}</div>}
    {onSignOut && <div className="account-settings"><p>{accountEmail}</p><button className="text-button" onClick={onSignOut} disabled={locked}>Sign out</button></div>}
  </>;
}
